server:
  servlet:
    context-path: /api

orders:
  queue:
    name: OrderMessages-Q

cloud:
  aws:
    region: us-east-1

logging:
  level:
    com.arthurtira.sbs: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

